# Generated by Django 3.0.3 on 2020-03-12 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attdc', '0072_auto_20200312_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tod_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 12, 17, 17, 693105)),
        ),
    ]
